id: A297EEBC4
base_file: fC4A9.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:18:31.391908
  last_modified_at: 2022-06-11 13:18:31.391916
